### ISSUE TITLE
Error in base/party.h

### ISSUE THREAD

**Issue by mayank-kabra2001** [encryptogroup/MOTION2NX#4]
I am seeing an error while compiling using cmake . Following are the commands I used. 
cd MOTION2NX/src/examples/example_template 
cmake . 
make 

Then I am getting the following error - 
/home/atom/MOTION2NX/src/examples/example_template/example_template_main.cpp:35:10: fatal error: base/party.h: No such file or directory
   35 | #include "base/party.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/example_template.dir/build.make:76: CMakeFiles/example_template.dir/example_template_main.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/example_template.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
![image](https://user-images.githubusercontent.com/57330493/145854463-5d201cf6-6d48-4d77-9cf8-7f5e56f5b149.png)

Attached is the screenshot of the error. 

Can someone help me out. 
Thanks.

**Comment by lenerd** [comment]
Yes, it won't work this way. You should reference the top-level `CMakeLists.txt`. The [README](https://github.com/encryptogroup/MOTION2NX#build-instructions) of this repository contains build instructions.

NB: The `example_template` example was written as an example for [MOTION](https://github.com/encryptogroup/MOTION). Since lots of things have changed, the new features implemented in MOTION**2NX** are currently not compatible with it.

**Comment by mayank-kabra2001** [comment]
Sorry, I did it wrong. Thanks !! 

Where should i see the output after using the build instruction mentioned in the readme?

**Comment by lenerd** [comment]
> Where should i see the output after using the build instruction mentioned in the readme?

Do you mean the compiled libraries/executables? In the build directory (in the example, it is `build_debwithrelinfo_gcc/`). The executables are then in the `bin/` subdirectory.
